version: '3.3'
services:
  backend:
    container_name: backend
    build:
      context: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_NAME: 'messages'
      DB_USER: 'root'
      DB_PASSWORD: '1234'
      DB_DIALECT: 'mysql'
      DB_HOST: 'db'
      DB_PORT: 3306

  db:
    container_name: db
    image: mysql:5.7.30
    restart: always
    environment:
      MYSQL_DATABASE: 'messages'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - node-p2-spa:/var/lib/mysql

volumes:
  node-p2-spa: