version: '3.3'
services:
    db:
        container_name: node-3-test-db
        image: mysql:5.7.30
        restart: always
        environment:
            MYSQL_DATABASE: 'mysql'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: '1234'
            MYSQL_ROOT_PASSWORD: '1234'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        volumes:
            - node-test-db:/var/lib/mysql
        networks:
            - node-test
    mongo:
        image: mongo:4.4.0
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        networks:
            - node-test

    mongo-express:
        image: mongo-express:0.54.0
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
        networks:
            - node-test

networks:
    node-test:
volumes:
    node-test-db: